### ISSUE TITLE
RQL rule changes in 2.*?

### ISSUE THREAD

**Issue by narcoticfresh** [xiag-ag/rql-parser#13]
Hi..

We are late trying to switch to 2.* in our graviton app, but now i tried that..

I'm a bit confused that also the RQL syntax seem to have changed in that release - the doc changes seemed like only internal/API changes were made.

The first change I encountered is that "." seems not to be a valid character for a field name now.. this breaks our syntax in our app - why was that changed?

Example:
In 1.* this was valid: `eq(name.test,Test)`
Now in 2.*, this is invalid, as it now states: `Invalid character "." at position 7`

Can this be added to the 2.* series or will this stay this way?
Currently I don't know if more changes were made..

Thanks

**Comment by mrix** [comment]
Hi @narcoticfresh .

Since the existing RQL documentation is very poor and ambiguous,
now this RQL parser requires that all non alphanumeric characters should be encoded in string values (including `-`).
This rule is partially valid for v1 too but it has been made stricter since v2.

Seems that you're using a patched `Lexer` class where some of restricted characters are decoded before lexing here https://github.com/libgraviton/php-rql-parser/blob/v2.3.1/src/Lexer.php#L29-L39.
In v2 the `Lexer` has been refactored. Now you can change some lexing rules via passing your own `SubLexer` to the `Lexer` constructor.

I prepared a simple example with "relaxed" encoding rules (see https://github.com/mrix/rql-parser-issue-13-demo/commits/master). I think such approach would be more appropriate for your requirements.

**Comment by narcoticfresh** [comment]
OK; no further actions needed
