### ISSUE TITLE
StringSubLexer doesn't support dots

### ISSUE THREAD

**Issue by dontub** [xiag-ag/rql-parser#8]
The StringSubLexer doesn't support values with dots. So for example this RQL leads to a SyntaxErrorException: `eq(x.id,1)`

**Comment by andreas-glaser** [comment]
Yes, please allow dots

**Comment by yansern** [comment]
Would `eq(x%2Eid,1)` work? I'm having trouble with underscores and I had to escape them as per the encoding rules seen here https://github.com/xiag-ag/rql-parser#encoding-rules

However, I think it's rather unintuitive because we would have to implement our codes this way `'eq(' . encodeString('x.id') . ',1)`. This makes me cringe.

**Comment by derrekbertrand** [comment]
I think in the long term, strings and identifiers should be separate tokens. For now, I've submitted a pull request.

**Comment by mrix** [comment]
See #10 .
